"""Add author category published_at to documents

Revision ID: 554e5f27f80f
Revises: 
Create Date: 2026-02-24 20:20:35.519741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554e5f27f80f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_author'), 'documents', ['author'], unique=False)
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_table('embedding_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),  # MySQLではString型を使用（キー長制限のため100文字）
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_cache_id'), 'embedding_cache', ['id'], unique=False)
    # MySQLではUNIQUEインデックスのキー長制限（3072バイト）を考慮
    # String(100)でutf8mb4の場合、最大400バイトなので問題なし
    op.create_index(op.f('ix_embedding_cache_text'), 'embedding_cache', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_cache_text'), table_name='embedding_cache')
    op.drop_index(op.f('ix_embedding_cache_id'), table_name='embedding_cache')
    op.drop_table('embedding_cache')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_author'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
