"""Add new features tables

Revision ID: 679355a4d157
Revises: 3a69b1a4697d
Create Date: 2026-02-27 17:35:23.877684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679355a4d157'
down_revision = '3a69b1a4697d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_links_source_document_id'), 'document_links', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_links_target_document_id'), 'document_links', ['target_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_links_target_document_id'), table_name='document_links')
    op.drop_index(op.f('ix_document_links_source_document_id'), table_name='document_links')
    # ### end Alembic commands ###
