"""Add analytics, mentions and document_links tables

Revision ID: a0016e927c89
Revises: 679355a4d157
Create Date: 2026-02-27 17:51:49.724529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0016e927c89'
down_revision = '679355a4d157'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # document_tagsテーブルを先に削除（外部キー制約があるため）
    op.drop_table('document_tags')
    # その後、tagsテーブルを削除
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.alter_column('document_links', 'link_type',
               existing_type=mysql.ENUM('MANUAL', 'AUTO', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('document_links', 'similarity_score',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('mentions', sa.Column('mentioned_document_id', sa.Integer(), nullable=False))
    op.alter_column('mentions', 'mention_text',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               nullable=True)
    op.drop_index(op.f('ix_mentions_target_id'), table_name='mentions')
    op.create_index(op.f('ix_mentions_mentioned_document_id'), 'mentions', ['mentioned_document_id'], unique=False)
    op.create_foreign_key(None, 'mentions', 'documents', ['mentioned_document_id'], ['id'])
    op.drop_column('mentions', 'target_id')
    op.drop_column('mentions', 'mention_type')
    op.alter_column('search_logs', 'query',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('search_logs', 'search_type',
               existing_type=mysql.ENUM('KEYWORD', 'SEMANTIC', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_logs', 'search_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('KEYWORD', 'SEMANTIC', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('search_logs', 'query',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               existing_nullable=False)
    op.add_column('mentions', sa.Column('mention_type', mysql.ENUM('DOCUMENT', 'USER', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('mentions', sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.drop_index(op.f('ix_mentions_mentioned_document_id'), table_name='mentions')
    op.create_index(op.f('ix_mentions_target_id'), 'mentions', ['target_id'], unique=False)
    op.alter_column('mentions', 'mention_text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('mentions', 'mentioned_document_id')
    op.alter_column('document_links', 'similarity_score',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('document_links', 'link_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('MANUAL', 'AUTO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.create_table('document_tags',
    sa.Column('document_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_tags_ibfk_1')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('document_tags_ibfk_2')),
    sa.PrimaryKeyConstraint('document_id', 'tag_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    # ### end Alembic commands ###
